apiVersion: apps/v1
kind: Secret
metadata:
   name: fluid-Ai-db
   namespace : fluid-Ai

type: Opaque 
stringData: 
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres123
   POSTGRES_DB: postgres

