name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: fluid-ai
  ECR_REGISTRY: 050721760237.dkr.ecr.us-east-1.amazonaws.com
  CLUSTER_NAME: fluid-ai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            ./app

      - name: Push Docker Image
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Verify Cluster Access
        run: |
          kubectl get nodes

      - name: Create Namespace
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Update Image In Manifest
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}|g" k8s/api.yml

      - name: Deploy Resources
        run: |
          kubectl apply -f k8s/secret.yml
          kubectl apply -f k8s/postgres.yml
          kubectl apply -f k8s/api.yml

      - name: Wait For Rollout
        run: |
          kubectl rollout status deployment/fluid-ai-api -n fluid-ai

      - name: Verify Deployment
        run: |
          kubectl get pods -n fluid-ai
          kubectl get svc -n fluid-ai
          kubectl get deployment -n fluid-ai